# HTTP Server (Tomcat) Port
server: 
  port: 8080
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: true

spring:
   application:
     name: point_of_sale_gateway
   main:
     allow-bean-definition-overriding: true
   cloud:
    metrics:
      enabled: true
    gateway:
      routes:
        - id: point_of_sale_auth
          uri: http://localhost:2222/
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment}
        - id: point_of_sale_crm
          uri:  http://localhost:3333/
          predicates:
            - Path=/crm/**
          filters:
            - RewritePath=/crm/(?<segment>.*), /$\{segment}
        - id: point_of_sale_item
          uri: http://localhost:4444/
          predicates:
            - Path=/item/**
          filters:
            - RewritePath=/item/(?<segment>.*), /$\{segment}
        - id: point_of_sale_ordering
          uri: http://localhost:5555/
          predicates:
            - Path=/ordering/**
          filters:
            - RewritePath=/ordering/(?<segment>.*), /$\{segment}
        - id: point_of_sale_payment
          uri: http://localhost:6666/
          predicates:
            - Path=/payment/**
          filters:
            - RewritePath=/payment/(?<segment>.*), /$\{segment}
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:1111/eureka/       