# HTTP Server (Tomcat) Port
server: 
  port: 8080
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: true
spring:
   application:
     name: point_of_sale_gateway
   main:
     allow-bean-definition-overriding: true
   cloud:
    gateway:
      routes:
        - id: point_of_sale_auth
          uri: http://localhost:2222
          predicates:
            - Path=/auth/**
        - id: point_of_sale_item
          uri: http://localhost:444
          predicates:
            - Path=/item/**

